FROM gagara/es-curator-arm64:6.0.0

# curator
COPY config.yml /etc/elasticsearch-curator
COPY actions.yml /etc/elasticsearch-curator
COPY backup.yml /etc/elasticsearch-curator
COPY restore.yml /etc/elasticsearch-curator

# fronius
RUN mkdir -p /opt/scheduler

COPY fronius_pull_stats.sh /opt/scheduler

RUN chmod 0775 /opt/scheduler/fronius_pull_stats.sh
