FROM gagara/elasticsearch-arm64:6.6.0

VOLUME /usr/share/elasticsearch/data

RUN set -ex; \
    echo "path.repo: [\"/usr/share/elasticsearch/data/backups\"]" >> /usr/share/elasticsearch/config/elasticsearch.yml

