FROM docker.elastic.co/logstash/logstash-oss:6.6.0

RUN set -ex; \
	curl -s -o /tmp/logstash-filter-elasticsearch.gem https://rubygems.org/downloads/logstash-filter-elasticsearch-3.6.0.gem && \
	curl -s -o /tmp/logstash-filter-aggregate.gem https://rubygems.org/downloads/logstash-filter-aggregate-2.9.0.gem && \
	/usr/share/logstash/bin/logstash-plugin install /tmp/logstash-filter-elasticsearch.gem /tmp/logstash-filter-aggregate.gem && \
	rm -f /tmp/logstash-filter-elasticsearch.gem /tmp/logstash-filter-aggregate.gem

ADD pipelines.yml /usr/share/logstash/config/pipelines.yml

ADD logstash_hk.conf /usr/share/logstash/pipeline/logstash_hk.conf
ADD template_hk.json /usr/share/logstash/config/template_hk.json 
ADD logstash_solar.conf /usr/share/logstash/pipeline/logstash_solar.conf
ADD template_solar.json /usr/share/logstash/config/template_solar.json 

CMD ["-w", "1"]

