version: '2'
services:

  elasticsearch:
    build:
      context: ./elasticsearch
    restart: unless-stopped
    ports:
      - "9200:9200"

  logstash:
    build:
      context: ./logstash
    restart: unless-stopped
    environment:
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
      - HK_PIPELINE_HOST=0.0.0.0
      - HK_PIPELINE_PORT=8085
      - FRONIUS_HOST=192.168.64.1
      - FRONIUS_PORT=7080
    ports:
      - "8085:8085"
      - "8065:8065"
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: ./kibana
    restart: unless-stopped
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  proxy:
    build:
      context: ./proxy
    tty: true
    restart: unless-stopped
    ports:
      - "8088:8088"
    depends_on:
      - elasticsearch
      - logstash

  curator:
    build:
      context: ./curator
    restart: unless-stopped
    depends_on:
      - elasticsearch

