version: '3'
services:

  elasticsearch:
    image: elasticsearch:5.2-alpine
    ports:
      - "9200:9200"

  logstash:
    build:
      context: ./logstash
    ports:
      - "8085:8085"
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:5.2
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

