version: '2'
services:

  elasticsearch:
    image: elasticsearch:2.4-alpine
    ports:
      - "9200:9200"

  logstash:
    build:
      context: ./logstash
    ports:
      - "8085:8085"
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:4.6
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

