version: '2'
services:

  elasticsearch:
    build:
      context: ./elasticsearch
      dockerfile: Dockerfile-amd64
    restart: unless-stopped
    environment:
      - cluster.name=homekeeper
      - node.name=node1
      - network.publish_host=127.0.0.1
      - discovery.zen.ping.unicast.hosts=127.0.0.1
    ports:
      - "9200:9200"
      - "9300:9300"

  logstash:
    build:
      context: ./logstash
      dockerfile: Dockerfile-amd64
    restart: unless-stopped
    environment:
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
      - HK_PIPELINE_HOST=0.0.0.0
      - HK_PIPELINE_PORT=8085
      - FRONIUS_PIPELINE_HOST=0.0.0.0
      - FRONIUS_PIPELINE_PORT=8086
      - GVDPR_UAC_MAX=265
      - GVDPR_REDUCTION_RATE=15
    ports:
      - "8085:8085"
      - "8086:8086"
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: ./kibana
      dockerfile: Dockerfile-amd64
    restart: unless-stopped
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile-amd64
    tty: true
    restart: unless-stopped
    environment:
      - FLASK_DEBUG=false
      - GATEWAY_USER=user
      - GATEWAY_PASSWORD=secret
      - DAD_HOST=127.0.0.1
      - DAD_PORT=80
      - MOM_HOST=127.0.0.1
      - MOM_PORT=80
    ports:
      - "8088:5000"
    depends_on:
      - elasticsearch
      - logstash

  scheduler:
    build:
      context: ./scheduler
      dockerfile: Dockerfile-amd64
    restart: unless-stopped
    environment:
      - FRONIUS_DEBUG=false
      - FRONIUS_HOST=fronius
      - FRONIUS_PORT=80
      - FRONIUS_PIPELINE_HOST=logstash
      - FRONIUS_PIPELINE_PORT=8086
      - FRONIUS_CURR_RQ_PULL_INTERVAL=1
      - FRONIUS_ARCH_RQ_PULL_INTERVAL=5
      - PRESERVE_ENV_VARS=FRONIUS_DEBUG FRONIUS_HOST FRONIUS_PORT FRONIUS_PIPELINE_HOST FRONIUS_PIPELINE_PORT FRONIUS_CURR_RQ_PULL_INTERVAL FRONIUS_ARCH_RQ_PULL_INTERVAL
    depends_on:
      - logstash
      - elasticsearch

